# Generated by Django 5.2.1 on 2025-05-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leo_stronda_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome2', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.TextField()),
            ],
        ),
    ]
